
# GitHub API authentication
import os
from dotenv import load_dotenv

load_dotenv()

GITHUB_ACCESS_TOKEN = os.getenv("GITHUB_ACCESS_TOKEN")

# OpenAI API authentication
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

FIXTHISCHRIS_SUPABASE_URL = os.getenv("FIXTHISCHRIS_SUPABASE_URL")
FIXTHISCHRIS_SUPABASE_ANON_KEY = os.getenv("FIXTHISCHRIS_SUPABASE_ANON_KEY")
FIXTHISCHRIS_SUPABASE_SERVICE_ROLE_KEY = os.getenv("FIXTHISCHRIS_SUPABASE_SERVICE_ROLE_KEY")
