
# GitHub API authentication
import os
from dotenv import load_dotenv

load_dotenv()

GITHUB_ACCESS_TOKEN = os.getenv("GITHUB_ACCESS_TOKEN")

# OpenAI API authentication
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

SOLVETHISJIM_SUPABASE_URL = os.getenv("SOLVETHISJIM_SUPABASE_URL")
SOLVETHISJIM_SUPABASE_ANON_KEY = os.getenv("SOLVETHISJIM_SUPABASE_ANON_KEY")
SOLVETHISJIM_SUPABASE_SERVICE_ROLE_KEY = os.getenv("SOLVETHISJIM_SUPABASE_SERVICE_ROLE_KEY")
